### ISSUE TITLE
Consider using THREE.PlaneBufferGeometry for lower memory footprint

### ISSUE THREAD

**Issue by msaunby** [informatics-lab/uk-weather-3d#2]
Threejs issues this warning for each of the PlaneGeometry instances.

THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint

It would be useful to look at how easy this is to implement. See http://threejs.org/docs/#Reference/Core/BufferGeometry

**Comment by felixturner** [comment]
IMO every usage of PlaneGeometry doesn't warrant a console log. Is it *that* bad?

**Comment by holographix** [comment]
+1

**Comment by YingshanDeng** [comment]
change to use  THREE.PlaneBufferGeometry is really a good idea to reduce memory?
